package com.wrb.csi.dao;

import org.apache.ibatis.annotations.Mapper;

import com.wrb.csi.model.Job;

@Mapper
public interface JobDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    int insertSelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    Job selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Job record);
}