package com.wrb.csi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.wrb.csi.model.User;

@Mapper
public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
    List<User> selectAllUsers();
    User selectByLoginName(String loginname);
    List<User> selectUserOnPage(int index, int pageSize);
    List<User> selectUserOnPageByStatus(int status, int index, int pageSize);
	List<User> selectUserOnPageByUsername(String username, int index, int pageSize);
	List<User> selectUserOnPageByUsernameAndStatus(String username, int status, int index, int pageSize);
	Integer getUserCount();
	Integer getUserCountByUsername(String username);
	Integer getUserCountByStatus(int status);
	Integer getUserCountByUsernameAndStatus(String username, int status);
   }